# .github/workflows/optic.yml
name: optic
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Optic
        run: npm install --location global @useoptic/optic

      - name: Build API
        run: dotnet build ./AspireShop.CatalogService/AspireShop.CatalogService.csproj

      - name: Diff Optic
        run: optic diff ./AspireShop.CatalogService/openapi.json --base origin/main --check --web --out optic.html

      - name: Convert HTML to Markdown
        id: html2markdown
        if: always()
        uses: rknj/html2markdown@v1.1.0
        with:
          html-file: "./optic.html"

      - name: Output to Job Summary
        if: always()
        run: echo '${{ steps.html2markdown.outputs.markdown-content }}' >> $GITHUB_STEP_SUMMARY
