# .github/workflows/optic.yml
name: optic
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Optic
        run: npm install --location global @useoptic/optic

      - name: Build API
        run: dotnet build ./AspireShop.CatalogService/AspireShop.CatalogService.csproj

      - name: Diff Optic
        run: optic diff ./AspireShop.CatalogService/openapi.json --base origin/main --check --web --out optic.html

      - name: Output Optic Diff as Job Summary
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            if(!fs.existsSync('optic.html')) {
              return;
            }
            const opticHtml = fs.readFileSync('optic.html', 'utf8');
            github.summary.addRaw(opticHtml).write();
