# .github/workflows/optic.yml
name: optic
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Optic
        run: npm install --location global @useoptic/optic

      - name: Build API
        run: dotnet build ./AspireShop.CatalogService/AspireShop.CatalogService.csproj

      - name: Diff Optic
        run: optic diff ./AspireShop.CatalogService/openapi.json --base origin/main --check
        env:
          CI: true

      - name: Parse Optic CI
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/parse-optic-ci.js');
            const results = fs.readFileSync('./ci-run-details.json', 'utf8');
            core.summary.addRaw(script({ context, results }));
